version: "3"

services:

  springBootApp:

    image: shoaibps19/person-entry:1.1

    container_name: docker-postgres-springboot-midproject-demo-app

    environment:

      - POSTGRES_HOST=docker-postgres-springboot-midproject-demo-db

    ports:

      - "8081:8099"

    networks:

      - network

    depends_on:

      - postgresDB

    restart: on-failure

  postgresDB:

    image: postgres:13.2

    container_name: docker-postgres-springboot-midproject-demo-db

    ports:

      - "5434:5432"

    networks:

      - network

    volumes:

      - volume:/var/lib/postgres/data

    environment:

      - POSTGRES_USER=postgres

      - POSTGRES_PASSWORD=Sapient@1910

      - POSTGRES_DB=person

networks:

  network:

volumes:

  volume: